"""
API router module for resume analysis endpoints.

This module provides FastAPI routers for various API endpoints including
resume upload, analysis, and job matching.
"""
from . import (
    analysis,
    analytics,
    ats_simulation,
    backups,
    batch,
    candidate_activities,
    candidate_notes,
    candidate_tags,
    candidates,
    comparisons,
    custom_synonyms,
    feedback,
    health,
    industry_classifier,
    matching,
    matching_weights,
    model_versions,
    performance_monitoring,
    ranking,
    reports,
    resumes,
    saved_searches,
    search,
    skill_gap_analysis,
    skill_suggestions,
    skill_taxonomies,
    taxonomy_import_export,
    taxonomy_sharing,
    taxonomy_versions,
    vacancies,
    work_experience,
    workflow_stages,
)

__all__ = [
    "analysis",
    "analytics",
    "ats_simulation",
    "backups",
    "batch",
    "candidate_activities",
    "candidate_notes",
    "candidate_tags",
    "candidates",
    "comparisons",
    "custom_synonyms",
    "feedback",
    "health",
    "industry_classifier",
    "matching",
    "matching_weights",
    "model_versions",
    "performance_monitoring",
    "ranking",
    "reports",
    "resumes",
    "saved_searches",
    "search",
    "skill_gap_analysis",
    "skill_suggestions",
    "skill_taxonomies",
    "taxonomy_import_export",
    "taxonomy_sharing",
    "taxonomy_versions",
    "vacancies",
    "work_experience",
    "workflow_stages",
]
