"""
Security utilities for password hashing and verification.

This module provides functions for securely hashing and verifying passwords
using bcrypt with proper work factor and salt management. Password hashing
is a critical security measure to protect user credentials even if the
database is compromised.

The bcrypt algorithm is used because it:
- Is computationally expensive (resistant to brute force attacks)
- Incorporates a unique salt for each password (prevents rainbow table attacks)
- Has a configurable work factor (can be made slower as hardware improves)
- Is widely battle-tested and recommended for password storage

Example usage:
    >>> from utils.security import get_password_hash, verify_password
    >>> hashed = get_password_hash("my_secure_password")
    >>> verify_password("my_secure_password", hashed)
    True
    >>> verify_password("wrong_password", hashed)
    False
"""
import logging
from typing import Optional

from passlib.context import CryptContext

logger = logging.getLogger(__name__)

# Password hashing context with bcrypt algorithm
# The work factor (12) means 2^12 iterations - provides good security vs performance balance
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto", bcrypt__rounds=12)


def get_password_hash(password: str) -> str:
    """
    Hash a password using bcrypt algorithm.

    This function takes a plain text password and returns a bcrypt hash.
    The hash includes a unique salt and the password hashed with the configured
    work factor. The resulting hash can be safely stored in the database.

    Security considerations:
    - Use a strong password (minimum 8 characters, mix of character types)
    - Never store plain text passwords
    - Each hash operation uses a unique salt automatically
    - The work factor (12 rounds) provides ~4096 hash iterations

    Args:
        password: Plain text password to hash. Should be pre-validated for
                  minimum length and complexity requirements before hashing.

    Returns:
        Bcrypt hash string (60 characters) in format:
        $2b$12$salt22charactersplus31characterhash
        This hash can be safely stored in the database.

    Raises:
        ValueError: If password is empty or None
        TypeError: If password is not a string

    Examples:
        >>> hash = get_password_hash("SecurePass123!")
        >>> len(hash)
        60
        >>> hash.startswith("$2b$12$")
        True

        >>> # Hashes are unique (due to random salt)
        >>> hash1 = get_password_hash("same_password")
        >>> hash2 = get_password_hash("same_password")
        >>> hash1 == hash2
        False
        >>> verify_password("same_password", hash1)
        True
        >>> verify_password("same_password", hash2)
        True
    """
    if not password:
        logger.error("Cannot hash empty or None password")
        raise ValueError("Password cannot be empty or None")

    if not isinstance(password, str):
        logger.error(f"Password must be a string, got {type(password)}")
        raise TypeError("Password must be a string")

    try:
        hashed = pwd_context.hash(password)
        logger.debug("Password hashed successfully")
        return hashed
    except Exception as e:
        logger.error(f"Failed to hash password: {e}")
        raise


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """
    Verify a plain text password against a bcrypt hash.

    This function securely compares a plain text password with a previously
    hashed password. It uses bcrypt's constant-time comparison to prevent
    timing attacks that could reveal information about the hash.

    Security features:
    - Constant-time comparison prevents timing attacks
    - Automatically extracts salt from the hash
    - Returns boolean only (no information about partial matches)

    Args:
        plain_password: Plain text password to verify. Should be the same
                       password that was originally hashed.
        hashed_password: Bcrypt hash to verify against. Should be a hash
                        previously generated by get_password_hash().

    Returns:
        True if the password matches the hash, False otherwise.
        A False return could mean:
        - Wrong password
        - Incorrect hash format
        - Hash corrupted or tampered with

    Raises:
        ValueError: If plain_password is empty or None
        TypeError: If inputs are not strings

    Examples:
        >>> hashed = get_password_hash("CorrectPassword123")
        >>> verify_password("CorrectPassword123", hashed)
        True
        >>> verify_password("WrongPassword", hashed)
        False
        >>> verify_password("", hashed)
        False

        >>> # Case sensitive
        >>> verify_password("correctpassword123", hashed)
        False

        >>> # Whitespace matters
        >>> verify_password("CorrectPassword123 ", hashed)
        False
    """
    if not plain_password:
        logger.error("Cannot verify empty or None password")
        raise ValueError("Plain password cannot be empty or None")

    if not isinstance(plain_password, str):
        logger.error(f"Plain password must be a string, got {type(plain_password)}")
        raise TypeError("Plain password must be a string")

    if not isinstance(hashed_password, str):
        logger.error(f"Hashed password must be a string, got {type(hashed_password)}")
        raise TypeError("Hashed password must be a string")

    try:
        is_valid = pwd_context.verify(plain_password, hashed_password)
        if is_valid:
            logger.debug("Password verification successful")
        else:
            logger.warning("Password verification failed - incorrect password")
        return is_valid
    except Exception as e:
        # Log the error but don't expose details that could help attackers
        logger.warning(f"Password verification failed: {e}")
        return False


def validate_password_strength(password: str) -> tuple[bool, Optional[str]]:
    """
    Validate password strength against security requirements.

    This function checks if a password meets minimum security requirements
    for user accounts. Password complexity rules help protect against
    brute force and dictionary attacks.

    Requirements:
    - Minimum 8 characters length
    - At least one lowercase letter (a-z)
    - At least one uppercase letter (A-Z)
    - At least one digit (0-9)
    - At least one special character (!@#$%^&*()_+-=[]{}|;:,.<>?)

    Args:
        password: Plain text password to validate

    Returns:
        Tuple of (is_valid, error_message):
        - (True, None) if password meets all requirements
        - (False, error_message) if password fails validation

    Examples:
        >>> validate_password_strength("weak")
        (False, 'Password must be at least 8 characters long')

        >>> validate_password_strength("weakpass")
        (False, 'Password must contain at least one uppercase letter')

        >>> validate_password_strength("WEAKPASS")
        (False, 'Password must contain at least one lowercase letter')

        >>> validate_password_strength("Weakpass")
        (False, 'Password must contain at least one digit')

        >>> validate_password_strength("Weakpass1")
        (False, 'Password must contain at least one special character')

        >>> validate_password_strength("WeakPass1!")
        (True, None)
    """
    if not password:
        return False, "Password cannot be empty"

    if len(password) < 8:
        return False, "Password must be at least 8 characters long"

    has_lower = any(c.islower() for c in password)
    if not has_lower:
        return False, "Password must contain at least one lowercase letter"

    has_upper = any(c.isupper() for c in password)
    if not has_upper:
        return False, "Password must contain at least one uppercase letter"

    has_digit = any(c.isdigit() for c in password)
    if not has_digit:
        return False, "Password must contain at least one digit"

    special_chars = "!@#$%^&*()_+-=[]{}|;:,.<>?"
    has_special = any(c in special_chars for c in password)
    if not has_special:
        return False, "Password must contain at least one special character"

    return True, None
