"""
Interview Preparation model for storing generated interview questions.
"""
from typing import Optional
from uuid import UUID

from sqlalchemy import ForeignKey, JSON, Text
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TimestampMixin, UUIDMixin


class InterviewPrep(Base, UUIDMixin, TimestampMixin):
    """
    Interview preparation data with generated questions.

    Stores interview questions generated by LLM based on resume
    and job vacancy analysis.

    Attributes:
        id: UUID primary key
        resume_id: Foreign key to Resume
        vacancy_id: Foreign key to JobVacancy
        technical_questions: List of technical interview questions
        behavioral_questions: List of behavioral interview questions
        situational_questions: List of situational interview questions
        skill_verification_topics: List of skills/experience to verify
        areas_to_probe: List of specific areas requiring deeper investigation
        custom_questions: List of recruiter-added custom questions
        question_feedback: Feedback on question usefulness
        provider: LLM provider used
        model: Model name used
        raw_response: Raw LLM response for debugging
    """

    __tablename__ = "interview_preps"

    # Reference to resume and vacancy
    resume_id: Mapped[UUID] = mapped_column(
        ForeignKey("resumes.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    vacancy_id: Mapped[UUID] = mapped_column(
        ForeignKey("job_vacancies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Generated questions by category
    technical_questions: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    behavioral_questions: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    situational_questions: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    skill_verification_topics: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    areas_to_probe: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)

    # Custom questions added by recruiters
    custom_questions: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)

    # Feedback on question usefulness
    question_feedback: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Metadata
    provider: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    model: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    raw_response: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return (
            f"<InterviewPrep(id={self.id}, resume_id={self.resume_id}, "
            f"vacancy_id={self.vacancy_id})>"
        )
