"""
ModelAlert model for tracking ML model alert history
"""
from typing import Optional

from sqlalchemy import JSON, String
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TimestampMixin, UUIDMixin


class ModelAlert(Base, UUIDMixin, TimestampMixin):
    """
    ModelAlert model for tracking ML model alert history

    This model stores alerts generated by the ML model lifecycle events,
    including performance degradation, training failures, version promotions,
    rollbacks, and other model-related notifications.

    Attributes:
        id: UUID primary key
        alert_type: Type of alert (performance_degradation, training_failure, etc.)
        model_name: Name of the model (e.g., ranking, skill_matching, resume_parser)
        severity: Alert severity level (info, warning, error, critical)
        title: Short alert title/heading
        message: Detailed alert message content
        details: JSON object with additional alert-specific data (metrics, versions, etc.)
        alert_id: Unique identifier for this alert (model:type:timestamp format)
        model_version_id: UUID reference to the related MLModelVersion (if applicable)
        previous_version_id: UUID reference to the previous model version (for rollbacks)
        status: Alert status (pending, sent, failed, acknowledged, resolved)
        channels: JSON list of channels the alert was sent through (email, slack, etc.)
        sent_at: ISO timestamp when the alert was sent
        acknowledged_at: ISO timestamp when the alert was acknowledged
        acknowledged_by: Email or ID of user who acknowledged the alert
        resolved_at: ISO timestamp when the alert was resolved
        resolution_notes: Optional notes about how the alert was resolved
        created_at: Timestamp when alert was created (inherited)
        updated_at: Timestamp when alert was last updated (inherited)
    """

    __tablename__ = "model_alerts"

    # Core alert fields
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    model_name: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="info")
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(String(2000), nullable=False)
    details: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Alert identification
    alert_id: Mapped[str] = mapped_column(String(200), nullable=False, unique=True, index=True)

    # Version references
    model_version_id: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    previous_version_id: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)

    # Alert lifecycle tracking
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending", index=True
    )
    channels: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    sent_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    acknowledged_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    acknowledged_by: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    resolved_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    resolution_notes: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)

    def __repr__(self) -> str:
        return f"<ModelAlert(id={self.id}, type={self.alert_type}, model={self.model_name}, severity={self.severity}, status={self.status})>"
